[package]
name = "iridium"
version = "0.1.0"
authors = ["Nick Calibey <nick.calibey@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "^4.0"
clap = { version = "2.32", features = ["yaml"] }
